name: Create New Repository

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Create repository
      id: create_repo
      run: |
        response=$(curl -X POST \
        -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/user/repos \
        -d "{\"name\":\"${{ github.event.inputs.repo_name }}\",\"private\":true}")
        
        repo_url=$(echo $response | jq -r '.html_url')
        echo "Repository URL: $repo_url"
        echo "::set-output name=repo_url::$repo_url"

    - name: Clone new repository
      run: |
        git clone https://x-access-token:${{ secrets.ORG_ADMIN_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.repository_name }}.git temp-repo

    - name: Copy files to new repository
      run: |
        rsync -av --progress . ./temp-repo --exclude .git --exclude temp-repo --exclude .github
      working-directory: ${{ github.workspace }}

    - name: Echo copied files
      run: |
        ls -a temp-repo

    - name: Commit and push files to new repository
      run: |
        cd temp-repo
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Initial commit from GitHub Action"
        git push origin main
