name: Create New Repository

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Create repository
      id: create_repo
      run: |
        response=$(curl -X POST \
        -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/user/repos \
        -d "{\"name\":\"${{ github.event.inputs.repo_name }}\",\"private\":true}")
                
        repo_url=$(echo $response | jq -r '.html_url')
        
        echo "Repository URL: $repo_url"
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
